# Generated by Django 3.2.16 on 2025-04-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_edge', '0046_auto_20250422_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprovider',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobprovider',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
