# Generated by Django 3.2.16 on 2025-05-02 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career_edge', '0047_auto_20250425_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCustomQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('question_type', models.CharField(choices=[('text', 'Text Answer'), ('yesno', 'Yes/No Answer'), ('file', 'File Upload'), ('link', 'Link (URL)')], default='text', max_length=10)),
                ('is_required', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_questions', to='career_edge.job')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplicationAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, null=True)),
                ('boolean_answer', models.BooleanField(blank=True, null=True)),
                ('file_answer', models.FileField(blank=True, null=True, upload_to='application_answers/')),
                ('link_answer', models.URLField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='career_edge.jobapplication')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_edge.jobcustomquestion')),
            ],
        ),
    ]
