# Generated by Django 3.2.16 on 2025-05-02 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_edge', '0048_jobapplicationanswer_jobcustomquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='has_custom_questions',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=10, validators=[django.core.validators.MinLengthValidator(10, message='Phone number must be at least 10 digits.'), django.core.validators.RegexValidator('^\\+?\\d{10,20}$', message='Enter a valid phone number.')]),
        ),
        migrations.AlterField(
            model_name='jobprovider',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
