# Generated by Django 3.2.16 on 2025-05-27 05:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_edge', '0049_auto_20250502_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (10-14 digits, optional + and country code).', regex='^\\+?1?\\d{10,14}$')]),
        ),
    ]
